#!/usr/bin/env node
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const __dirname = dirname(fileURLToPath(import.meta.url));

const HELP = `
ultra-dev ERD generator

Usage:
  node scripts/erd/erd.mjs --db <postgres|sqlite|sqlserver> --conn <string> --out <dir> [options]

Options:
  --db        DB engine: postgres | sqlite | sqlserver
  --conn      Connection string (postgres / sqlserver) or file path (sqlite)
  --out       Output directory (writes erd.md + erd.html)
  --schema    Schema name (postgres default: public; sqlserver default: dbo)
  --title     Diagram title (default: "Database ERD")
  -h, --help  Show this message

Examples:
  node scripts/erd/erd.mjs --db postgres   --conn "$DATABASE_URL"            --out docs/ultra-dev/users-feature
  node scripts/erd/erd.mjs --db sqlite     --conn ./app.db                    --out docs/ultra-dev/users-feature
  node scripts/erd/erd.mjs --db sqlserver  --conn "Server=localhost;Database=app;User Id=sa;Password=x;TrustServerCertificate=true" --out docs/ultra-dev/users-feature

Drivers (install only the one you need):
  postgres   → npm install pg
  sqlite     → npm install better-sqlite3
  sqlserver  → npm install mssql
`;

const { values } = parseArgs({
  options: {
    db: { type: 'string' },
    conn: { type: 'string' },
    out: { type: 'string' },
    schema: { type: 'string' },
    title: { type: 'string', default: 'Database ERD' },
    help: { type: 'boolean', short: 'h' },
  },
});

if (values.help) {
  console.log(HELP);
  process.exit(0);
}

if (!values.db || !values.conn || !values.out) {
  console.error(HELP);
  console.error('Error: --db, --conn, and --out are required.');
  process.exit(1);
}

const introspectors = {
  postgres: () => import('./queries/postgres.mjs'),
  sqlite: () => import('./queries/sqlite.mjs'),
  sqlserver: () => import('./queries/sqlserver.mjs'),
};

if (!introspectors[values.db]) {
  console.error(`Unknown --db: ${values.db}. Supported: postgres, sqlite, sqlserver.`);
  process.exit(1);
}

const driverPkg = { postgres: 'pg', sqlite: 'better-sqlite3', sqlserver: 'mssql' }[values.db];
const schemaDefault = { postgres: 'public', sqlite: undefined, sqlserver: 'dbo' }[values.db];

let schema;
try {
  const mod = await introspectors[values.db]();
  schema = await mod.introspect({ conn: values.conn, schema: values.schema ?? schemaDefault });
} catch (e) {
  if (
    e.code === 'ERR_MODULE_NOT_FOUND' ||
    e.code === 'MODULE_NOT_FOUND' ||
    /Cannot find (?:package|module)/.test(e.message)
  ) {
    console.error(`Missing dependency. Run: npm install ${driverPkg}`);
    process.exit(2);
  }
  console.error(`Introspection failed: ${e.message}`);
  process.exit(1);
}

if (!schema.tables.length) {
  console.error('No tables found. Check the connection string and schema name.');
  process.exit(3);
}

const mermaid = renderMermaid(schema);

mkdirSync(values.out, { recursive: true });
const mdPath = join(values.out, 'erd.md');
const htmlPath = join(values.out, 'erd.html');
writeMd(mdPath, values.title, mermaid, schema);
writeHtml(htmlPath, values.title, mermaid);

console.log(`Wrote:`);
console.log(`  ${mdPath}`);
console.log(`  ${htmlPath}`);
console.log(`Open the .html file in a browser to view the diagram.`);

function renderMermaid({ tables, fks }) {
  const lines = ['erDiagram'];
  for (const t of tables) {
    lines.push(`    ${ident(t.name)} {`);
    for (const c of t.columns) {
      const tags = [c.pk && 'PK', c.fk && 'FK'].filter(Boolean).join(',');
      const note = c.nullable === false ? ' "not null"' : '';
      lines.push(`        ${ident(c.type || 'unknown')} ${ident(c.name)}${tags ? ' ' + tags : ''}${note}`);
    }
    lines.push('    }');
  }
  for (const fk of fks) {
    const optional = fk.optional ? 'o' : '|';
    const label = (fk.label || fk.name || 'fk').replace(/"/g, "'");
    lines.push(`    ${ident(fk.parent)} ||--${optional}{ ${ident(fk.child)} : "${label}"`);
  }
  return lines.join('\n');
}

function ident(s) {
  const v = String(s ?? '').replace(/[^a-zA-Z0-9_]/g, '_');
  return v.length ? v : '_';
}

function writeMd(path, title, mermaid, schema) {
  const summary = `${schema.tables.length} table(s), ${schema.fks.length} foreign key(s).`;
  const body =
    `# ${title}\n\n` +
    `Generated by ultra-dev-plugin ERD script. ${summary}\n\n` +
    '```mermaid\n' + mermaid + '\n```\n';
  writeFileSync(path, body, 'utf8');
}

function writeHtml(path, title, mermaid) {
  const tpl = readFileSync(join(__dirname, 'template.html'), 'utf8');
  const safe = mermaid.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const safeTitle = String(title).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const body = tpl.replaceAll('{{TITLE}}', safeTitle).replaceAll('{{DIAGRAM}}', safe);
  writeFileSync(path, body, 'utf8');
}
